<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gpu_slam_bot">

  <!-- Robot parameters -->
  <xacro:property name="base_radius" value="0.225"/> <!-- Equivalent to your length/2 -->
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_separation" value="0.35"/>
  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="pusher_depth" value="0.05"/>
  <xacro:property name="pusher_width" value="0.20"/>
  <xacro:property name="pusher_height" value="0.06"/>
  <xacro:property name="arm_length" value="0.08"/>
  <xacro:property name="tip_length" value="0.08"/>
  <xacro:property name="arm_radius" value="0.01"/>
  <xacro:property name="sphere_radius" value="0.015"/>
  <xacro:property name="arm_mass" value="0.05"/>
  <xacro:property name="tip_mass" value="0.05"/>
  <xacro:property name="sphere_mass" value="0.015"/>
  <xacro:property name="gripper_arm_separation" value="0.10"/>
  <xacro:property name="curve_angle" value="0.349"/>

  <!-- Materials -->
  <material name="metallic_gray"><color rgba="0.7 0.7 0.75 1"/></material>
  <material name="wheel_black"><color rgba="0 0 0 1"/></material>
  <material name="stripe_green"><color rgba="0 1 0 1"/></material>
  <material name="pusher_red"><color rgba="1 0 0 1"/></material>

  <!-- Base link - Now cylindrical for round appearance -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="3.0"/>
      <inertia ixx="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               iyy="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               izz="${0.5*3.0*base_radius*base_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Lidar -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="0.055"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.03" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.06" radius="0.055"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.03"/>
      <mass value="0.2"/>
      <inertia ixx="0.0004" iyy="0.0004" izz="0.0003" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${base_height/2 + 0.03}" rpy="0 0 0"/>
  </joint>

  <!-- Left Wheel -->
  <link name="wheel_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Right Wheel -->
  <link name="wheel_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Wheel joints -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="0 ${wheel_separation/2} ${-wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="0 ${-wheel_separation/2} ${-wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Caster - Adjusted position for cylindrical base -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${caster_radius}"/></geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${caster_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(2/5)*0.1*caster_radius*caster_radius}"
               iyy="${(2/5)*0.1*caster_radius*caster_radius}"
               izz="${(2/5)*0.1*caster_radius*caster_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="-${base_radius - 0.05} 0 ${-wheel_radius + caster_radius - 0.005}" rpy="0 0 0"/>
  </joint>

  <!-- Gripper base -->
  <link name="gripper_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${pusher_depth} ${pusher_width} ${pusher_height}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${pusher_depth} ${pusher_width} ${pusher_height}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(1/12)*0.1*(pusher_width*pusher_width + pusher_height*pusher_height)}"
               iyy="${(1/12)*0.1*(pusher_depth*pusher_depth + pusher_height*pusher_height)}"
               izz="${(1/12)*0.1*(pusher_depth*pusher_depth + pusher_width*pusher_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="front_lifter_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="gripper_base_link"/>
    <origin xyz="${base_radius + pusher_depth/2} 0 ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="15" velocity="0.2" lower="0.0" upper="0.25"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Left gripper arm (proximal) -->
  <link name="left_arm_link">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${arm_mass}"/>
      <inertia ixx="${0.5 * arm_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               izz="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_gripper_joint" type="revolute">
    <parent link="gripper_base_link"/>
    <child link="left_arm_link"/>
    <origin xyz="0 ${gripper_arm_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="2.0" lower="-0.523" upper="0.523"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <!-- Left tip (distal, curved) -->
  <link name="left_tip_link">
    <visual>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${0.5 * tip_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               izz="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_tip_joint" type="fixed">
    <parent link="left_arm_link"/>
    <child link="left_tip_link"/>
    <origin xyz="${arm_length} 0 0" rpy="0 0 -${curve_angle}"/>
  </joint>

  <!-- Left tip sphere (rounded tip) -->
  <link name="left_sphere_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision name="left_sphere_link_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${sphere_mass}"/>
      <inertia ixx="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               iyy="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               izz="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_sphere_joint" type="fixed">
    <parent link="left_tip_link"/>
    <child link="left_sphere_link"/>
    <origin xyz="${tip_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Right gripper arm (proximal) -->
  <link name="right_arm_link">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${arm_mass}"/>
      <inertia ixx="${0.5 * arm_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               izz="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_gripper_joint" type="revolute">
    <parent link="gripper_base_link"/>
    <child link="right_arm_link"/>
    <origin xyz="0 ${-gripper_arm_separation/2} 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="30" velocity="2.0" lower="-0.523" upper="0.523"/>
    <dynamics damping="0.2" friction="0.05"/>
    <mimic joint="left_gripper_joint" multiplier="-1" offset="0"/>
  </joint>

  <!-- Right tip (distal, curved) -->
  <link name="right_tip_link">
    <visual>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${0.5 * tip_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               izz="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_tip_joint" type="fixed">
    <parent link="right_arm_link"/>
    <child link="right_tip_link"/>
    <origin xyz="${arm_length} 0 0" rpy="0 0 ${curve_angle}"/>
  </joint>

  <!-- Right tip sphere (rounded tip) -->
  <link name="right_sphere_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision name="right_sphere_link_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${sphere_mass}"/>
      <inertia ixx="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               iyy="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               izz="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_sphere_joint" type="fixed">
    <parent link="right_tip_link"/>
    <child link="right_sphere_link"/>
    <origin xyz="${tip_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Contact sensors -->
  <gazebo reference="left_sphere_link">
    <sensor name="left_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>200</update_rate>
      <contact>
        <collision>left_sphere_link_collision</collision>
      </contact>
      <plugin name="left_contact_plugin" filename="libgazebo_ros_contact.so">
        <ros>
          <namespace>/</namespace>
          <remapping>left_gripper_contact:=left_gripper_contact</remapping>
        </ros>
        <topic_name>left_gripper_contact</topic_name>
        <frame_name>left_sphere_link</frame_name>
      </plugin>
    </sensor>
    <material>Gazebo/Red</material>
    <surface>
      <friction>
        <ode>
          <mu>0.4</mu>
          <mu2>0.4</mu2>
        </ode>
      </friction>
      <bounce>
        <restitution_coefficient>0.05</restitution_coefficient>
        <threshold>0.01</threshold>
      </bounce>
    </surface>
  </gazebo>

  <gazebo reference="right_sphere_link">
    <sensor name="right_contact_sensor" type="contact">
      <always_on>true</always_on>
      <update_rate>200</update_rate>
      <contact>
        <collision>right_sphere_link_collision</collision>
      </contact>
      <plugin name="right_contact_plugin" filename="libgazebo_ros_contact.so">
        <ros>
          <namespace>/</namespace>
          <remapping>right_gripper_contact:=right_gripper_contact</remapping>
        </ros>
        <topic_name>right_gripper_contact</topic_name>
        <frame_name>right_sphere_link</frame_name>
      </plugin>
    </sensor>
    <material>Gazebo/Red</material>
    <surface>
      <friction>
        <ode>
          <mu>0.4</mu>
          <mu2>0.4</mu2>
        </ode>
      </friction>
      <bounce>
        <restitution_coefficient>0.05</restitution_coefficient>
        <threshold>0.01</threshold>
      </bounce>
    </surface>
  </gazebo>

  <!-- Gazebo diff_drive plugin -->
  <gazebo>
    <plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>100</update_rate>
      <left_joint>wheel_left_joint</left_joint>
      <right_joint>wheel_right_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>75.0</max_wheel_torque>
      <max_wheel_acceleration>15.0</max_wheel_acceleration>
      <command_topic>cmd_vel</command_topic>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
      <publish_odom>true</publish_odom>
      <publish_wheel_tf>true</publish_wheel_tf>
      <publish_tf>true</publish_tf>
      <publish_odom_tf>true</publish_odom_tf>
    </plugin>
  </gazebo>

  <!-- Gazebo plugin for lifter control -->
  <gazebo>
    <plugin name="lifter_position_controller" filename="libgazebo_ros_joint_pose_trajectory.so">
      <ros>
        <namespace>/</namespace>
        <remapping>front_lifter_cmd:=front_lifter_cmd</remapping>
      </ros>
      <joint_name>front_lifter_joint</joint_name>
      <topic_name>front_lifter_cmd</topic_name>
    </plugin>
  </gazebo>

  <!-- Gazebo plugin for left gripper control -->
  <gazebo>
    <plugin name="gripper_position_controller_left" filename="libgazebo_ros_joint_pose_trajectory.so">
      <ros>
        <namespace>/</namespace>
        <remapping>gripper_cmd:=gripper_cmd</remapping>
      </ros>
      <joint_name>left_gripper_joint</joint_name>
      <topic_name>gripper_cmd</topic_name>
    </plugin>
  </gazebo>

  <!-- Gazebo plugin for right gripper control -->
  <gazebo>
    <plugin name="gripper_position_controller_right" filename="libgazebo_ros_joint_pose_trajectory.so">
      <ros>
        <namespace>/</namespace>
        <remapping>gripper_cmd:=gripper_cmd</remapping>
      </ros>
      <joint_name>right_gripper_joint</joint_name>
      <topic_name>gripper_cmd</topic_name>
    </plugin>
  </gazebo>

  <!-- Gazebo materials and physics -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="lidar_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  
  <gazebo reference="gripper_base_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_tip_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="right_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="right_tip_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- Wheel physics properties -->
  <gazebo reference="wheel_left">
    <material>Gazebo/Black</material>
    <surface>
      <friction>
        <ode>
          <mu>1.2</mu>
          <mu2>1.2</mu2>
          <fdir1>1 0 0</fdir1>
          <slip1>0.0</slip1>
          <slip2>0.0</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <gazebo reference="wheel_right">
    <material>Gazebo/Black</material>
    <surface>
      <friction>
        <ode>
          <mu>1.2</mu>
          <mu2>1.2</mu2>
          <fdir1>1 0 0</fdir1>
          <slip1>0.0</slip1>
          <slip2>0.0</slip2>
        </ode>
      </friction>
    </surface>
  </gazebo>

  <!-- Caster physics -->
  <gazebo reference="caster_link">
    <material>Gazebo/Grey</material>
    <surface>
      <friction>
        <ode>
          <mu>0.01</mu>
          <mu2>0.01</mu2>
        </ode>
      </friction>
    </surface>
  </gazebo>

</robot>