<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gpu_slam_bot">
  <!-- Updated Robot Parameters -->
  <xacro:property name="base_radius" value="0.225"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_separation" value="0.40"/>
  <xacro:property name="caster_radius" value="0.03"/>
  <xacro:property name="pusher_depth" value="0.05"/>
  <xacro:property name="pusher_width" value="0.20"/>
  <xacro:property name="pusher_height" value="0.06"/>
  <xacro:property name="arm_length" value="0.12"/>
  <xacro:property name="tip_length" value="0.12"/>
  <xacro:property name="arm_radius" value="0.015"/>
  <xacro:property name="sphere_radius" value="0.02"/>
  <xacro:property name="arm_mass" value="0.07"/>
  <xacro:property name="tip_mass" value="0.07"/>
  <xacro:property name="sphere_mass" value="0.02"/>
  <xacro:property name="gripper_arm_separation" value="0.18"/> <!-- Reduced from 0.22 for compactness -->
  <xacro:property name="curve_angle" value="0.349"/>

  <!-- Materials -->
  <material name="metallic_gray"><color rgba="0.7 0.7 0.75 1"/></material>
  <material name="wheel_black"><color rgba="0 0 0 1"/></material>
  <material name="stripe_green"><color rgba="0 1 0 1"/></material>
  <material name="pusher_red"><color rgba="1 0 0 1"/></material>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="3.0"/>
      <inertia ixx="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               iyy="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               izz="${0.5*3.0*base_radius*base_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Wheels -->
  <link name="wheel_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="wheel_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="0 ${wheel_separation/2} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="0 ${-wheel_separation/2} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <!-- Lifter link (shortened height from 0.2m to 0.1m) -->
  <link name="lifter_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.8</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <mass value="0.1"/> <!-- Reduced from 0.2 to reflect smaller size -->
      <inertia ixx="${(1/12)*0.1*(0.05*0.05 + 0.1*0.1)}"
               iyy="${(1/12)*0.1*(0.05*0.05 + 0.1*0.1)}"
               izz="${(1/12)*0.1*(0.05*0.05 + 0.05*0.05)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="front_lifter_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="lifter_link"/>
    <origin xyz="${base_radius} 0 ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="15" velocity="0.2" lower="0.0" upper="0.4"/> <!-- Increased upper limit to 0.4m -->
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- Left gripper arm -->
  <link name="left_arm_link">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${arm_mass}"/>
      <inertia ixx="${0.5 * arm_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               izz="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_gripper_joint" type="revolute">
    <parent link="lifter_link"/>
    <child link="left_arm_link"/>
    <origin xyz="0 ${gripper_arm_separation/2} 0.05" rpy="0 0 0"/> <!-- Adjusted z to 0.05m -->
    <axis xyz="0 0 1"/>
    <limit effort="20" velocity="2.0" lower="-0.6" upper="0.6"/>
    <dynamics damping="0.3" friction="0.05"/>
  </joint>

  <!-- Left tip -->
  <link name="left_tip_link">
    <visual>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${0.5 * tip_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               izz="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_tip_joint" type="fixed">
    <parent link="left_arm_link"/>
    <child link="left_tip_link"/>
    <origin xyz="${arm_length} 0 0" rpy="0 0 -${curve_angle}"/>
  </joint>

  <!-- Left tip sphere -->
  <link name="left_sphere_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision name="left_sphere_link_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${sphere_mass}"/>
      <inertia ixx="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               iyy="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               izz="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_sphere_joint" type="fixed">
    <parent link="left_tip_link"/>
    <child link="left_sphere_link"/>
    <origin xyz="${tip_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Right gripper arm -->
  <link name="right_arm_link">
    <visual>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${arm_length}" radius="${arm_radius}"/></geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${arm_mass}"/>
      <inertia ixx="${0.5 * arm_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               izz="${(1/4)*arm_mass*arm_radius*arm_radius + (1/12)*arm_mass*arm_length*arm_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_gripper_joint" type="revolute">
    <parent link="lifter_link"/>
    <child link="right_arm_link"/>
    <origin xyz="0 ${-gripper_arm_separation/2} 0.05" rpy="0 0 0"/> <!-- Adjusted z to 0.05m -->
    <axis xyz="0 0 1"/>
    <limit effort="20" velocity="2.0" lower="-0.6" upper="0.6"/>
    <dynamics damping="0.3" friction="0.05"/>
    <mimic joint="left_gripper_joint" multiplier="-1" offset="0"/>
  </joint>

  <!-- Right tip -->
  <link name="right_tip_link">
    <visual>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision>
      <origin xyz="${tip_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry><cylinder length="${tip_length}" radius="${arm_radius}"/></geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${0.5 * tip_mass * arm_radius * arm_radius}"
               iyy="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               izz="${(1/4)*tip_mass*arm_radius*arm_radius + (1/12)*tip_mass*tip_length*tip_length}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_tip_joint" type="fixed">
    <parent link="right_arm_link"/>
    <child link="right_tip_link"/>
    <origin xyz="${arm_length} 0 0" rpy="0 0 ${curve_angle}"/>
  </joint>

  <!-- Right tip sphere -->
  <link name="right_sphere_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
      <material name="pusher_red"/>
    </visual>
    <collision name="right_sphere_link_collision">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><sphere radius="${sphere_radius}"/></geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${sphere_mass}"/>
      <inertia ixx="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               iyy="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               izz="${(2/5)*sphere_mass*sphere_radius*sphere_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_sphere_joint" type="fixed">
    <parent link="right_tip_link"/>
    <child link="right_sphere_link"/>
    <origin xyz="${tip_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Caster wheel for stability -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(2/5)*0.1*caster_radius*caster_radius}"
               iyy="${(2/5)*0.1*caster_radius*caster_radius}"
               izz="${(2/5)*0.1*caster_radius*caster_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="${-base_radius} 0 ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Back platform for additional payload or sensors -->
  <link name="back_platform_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_radius*2} 0.1 ${base_height/2}"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_radius*2} 0.1 ${base_height/2}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="back_platform_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_platform_link"/>
    <origin xyz="${-base_radius} 0 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Placeholder for lidar sensor (raised for better visibility) -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.05"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${base_height + 0.05}" rpy="0 0 0"/> <!-- Raised by 0.05m -->
  </joint>

  <!-- ================ GAZEBO PLUGINS ================ -->
  <!-- Differential Drive Controller Plugin -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>30</update_rate>
      <left_joint>wheel_left_joint</left_joint>
      <right_joint>wheel_right_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>30</max_wheel_torque> <!-- Increased from 20 -->
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <command_topic>cmd_vel/gripper</command_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <!-- Joint State Publisher Plugin -->
  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>50</update_rate>
      <joint_name>wheel_left_joint</joint_name>
      <joint_name>wheel_right_joint</joint_name>
      <joint_name>front_lifter_joint</joint_name>
      <joint_name>left_gripper_joint</joint_name>
      <joint_name>right_gripper_joint</joint_name>
      <joint_name>caster_joint</joint_name>
    </plugin>
  </gazebo>

  <!-- Laser Scanner Plugin -->
  <gazebo reference="lidar_link">
    <sensor type="ray" name="laser_scanner">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <topicName>scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <!-- Joint Position Controllers for Gripper and Lifter -->
  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find gpu_slam_bot)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Gazebo material properties -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="wheel_left">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1> <!-- Increased from 0.8 -->
    <mu2>1.0</mu2> <!-- Increased from 0.8 -->
  </gazebo>
  <gazebo reference="wheel_right">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1> <!-- Increased from 0.8 -->
    <mu2>1.0</mu2> <!-- Increased from 0.8 -->
  </gazebo>
  <gazebo reference="caster_link">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>
  <gazebo reference="lifter_link">
    <material>Gazebo/Grey</material>
  </gazebo>
  <gazebo reference="left_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>
  <gazebo reference="right_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <!-- ===================== TRANSMISSIONS ===================== -->
  <!-- Left Gripper Transmission -->
  <transmission name="left_gripper_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_gripper_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_gripper_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Right Gripper Transmission (mimics left) -->
  <transmission name="right_gripper_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_gripper_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_gripper_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- Front Lifter Transmission -->
  <transmission name="lifter_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="front_lifter_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="lifter_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>