<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="gpu_slam_bot">
  <!-- Robot Parameters -->
  <xacro:property name="base_radius" value="0.225"/>
  <xacro:property name="base_height" value="0.08"/>
  <xacro:property name="wheel_radius" value="0.04"/>
  <xacro:property name="wheel_width" value="0.06"/>
  <xacro:property name="wheel_separation" value="0.40"/>
  <xacro:property name="caster_radius" value="0.03"/>
  
  <!-- Enhanced Gripper Parameters -->
  <xacro:property name="gripper_base_height" value="0.15"/>
  <xacro:property name="gripper_base_width" value="0.25"/>
  <xacro:property name="upper_arm_length" value="0.12"/>
  <xacro:property name="forearm_length" value="0.14"/>
  <xacro:property name="forearm_radius" value="0.02"/>
  <xacro:property name="gripper_finger_length" value="0.12"/>
  <xacro:property name="arm_radius" value="0.015"/>
  <xacro:property name="finger_radius" value="0.008"/>
  <xacro:property name="gripper_tip_radius" value="0.012"/>
  
  <!-- Masses -->
  <xacro:property name="gripper_base_mass" value="0.5"/>
  <xacro:property name="upper_arm_mass" value="0.3"/>
  <xacro:property name="forearm_mass" value="0.2"/>
  <xacro:property name="finger_mass" value="0.1"/>
  <xacro:property name="tip_mass" value="0.05"/>

  <!-- Morandi Colors -->
  <material name="morandi_sage"><color rgba="0.7 0.8 0.7 1"/></material>
  <material name="morandi_dusty_pink"><color rgba="0.85 0.75 0.8 1"/></material>
  <material name="morandi_warm_gray"><color rgba="0.75 0.73 0.7 1"/></material>
  <material name="morandi_soft_blue"><color rgba="0.7 0.78 0.85 1"/></material>
  <material name="metallic_gray"><color rgba="0.7 0.7 0.75 1"/></material>
  <material name="wheel_black"><color rgba="0 0 0 1"/></material>
  <material name="gripper_red"><color rgba="0.9 0.3 0.3 1"/></material>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${base_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="3.0"/>
      <inertia ixx="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               iyy="${(1/12)*3.0*(3*base_radius*base_radius + base_height*base_height)}"
               izz="${0.5*3.0*base_radius*base_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Wheels -->
  <link name="wheel_left">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="wheel_right">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="1.5"/>
      <inertia ixx="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               iyy="${0.5*1.5*wheel_radius*wheel_radius}"
               izz="${(1/12)*1.5*(3*wheel_radius*wheel_radius + wheel_width*wheel_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left"/>
    <origin xyz="0 ${wheel_separation/2} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right"/>
    <origin xyz="0 ${-wheel_separation/2} ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.2" friction="0.0"/>
  </joint>

  <!-- Caster wheel -->
  <link name="caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(2/5)*0.1*caster_radius*caster_radius}"
               iyy="${(2/5)*0.1*caster_radius*caster_radius}"
               izz="${(2/5)*0.1*caster_radius*caster_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="caster_link"/>
    <origin xyz="${-base_radius} 0 ${-base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Gripper Base Platform (vertical motion) - Lower initial position -->
  <link name="gripper_base_link">
    <visual>
      <geometry>
        <box size="0.08 ${gripper_base_width} ${gripper_base_height}"/>
      </geometry>
      <material name="morandi_warm_gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.08 ${gripper_base_width} ${gripper_base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${gripper_base_mass}"/>
      <inertia ixx="${(1/12)*gripper_base_mass*(gripper_base_width*gripper_base_width + gripper_base_height*gripper_base_height)}"
               iyy="${(1/12)*gripper_base_mass*(0.08*0.08 + gripper_base_height*gripper_base_height)}"
               izz="${(1/12)*gripper_base_mass*(0.08*0.08 + gripper_base_width*gripper_base_width)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <!-- Lower initial position and increased range for gripper lift -->
  <joint name="gripper_lift_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="gripper_base_link"/>
    <origin xyz="0.18 0 ${base_height/2 + 0.08}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="50" velocity="0.5" lower="0.0" upper="0.6"/>
    <dynamics damping="0.5" friction="0.2"/>
  </joint>

  <!-- Left Gripper Arm Assembly -->
  <!-- Left shoulder (horizontal swing) - FIXED CONSTRAINTS -->
  <link name="left_shoulder_link">
    <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(1/12)*0.1*(3*0.02*0.02 + 0.04*0.04)}"
               iyy="${(1/12)*0.1*(3*0.02*0.02 + 0.04*0.04)}"
               izz="${0.5*0.1*0.02*0.02}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_shoulder_joint" type="revolute">
    <parent link="gripper_base_link"/>
    <child link="left_shoulder_link"/>
    <origin xyz="0 ${gripper_base_width/3} 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- FIXED: Prevent backward bending into body -->
    <limit effort="30" velocity="2.0" lower="-0.5" upper="1.2"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- Left upper arm (vertical swing) - FIXED CONSTRAINTS -->
  <link name="left_upper_arm_link">
    <visual>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${upper_arm_length/2} 0 0"/>
      <mass value="${upper_arm_mass}"/>
      <inertia ixx="${(1/12)*upper_arm_mass*(3*arm_radius*arm_radius + upper_arm_length*upper_arm_length)}"
               iyy="${(1/12)*upper_arm_mass*(3*arm_radius*arm_radius + upper_arm_length*upper_arm_length)}"
               izz="${0.5*upper_arm_mass*arm_radius*arm_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_shoulder_pitch_joint" type="revolute">
    <parent link="left_shoulder_link"/>
    <child link="left_upper_arm_link"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- FIXED: Prevent upward bending that causes body collision -->
    <limit effort="30" velocity="2.0" lower="-0.8" upper="0.3"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- Left elbow - FIXED CONSTRAINTS -->
  <link name="left_elbow_link">
    <visual>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="${(2/5)*0.05*0.015*0.015}"
               iyy="${(2/5)*0.05*0.015*0.015}"
               izz="${(2/5)*0.05*0.015*0.015}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_elbow_joint" type="revolute">
    <parent link="left_upper_arm_link"/>
    <child link="left_elbow_link"/>
    <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- FIXED: Prevent hyper-extension backward -->
    <limit effort="20" velocity="3.0" lower="-0.5" upper="1.8"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <!-- Left forearm -->
  <link name="left_forearm_link">
    <visual>
      <origin xyz="${forearm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${forearm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${forearm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${forearm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${forearm_length/2} 0 0"/>
      <mass value="${forearm_mass}"/>
      <inertia ixx="${(1/12)*forearm_mass*(3*arm_radius*arm_radius + forearm_length*forearm_length)}"
               iyy="${(1/12)*forearm_mass*(3*arm_radius*arm_radius + forearm_length*forearm_length)}"
               izz="${0.5*forearm_mass*arm_radius*arm_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_forearm_joint" type="fixed">
    <parent link="left_elbow_link"/>
    <child link="left_forearm_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Left wrist - FIXED CONSTRAINTS -->
  <link name="left_wrist_link">
    <visual>
      <geometry>
        <cylinder length="0.03" radius="0.01"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.03" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.03"/>
      <inertia ixx="${(1/12)*0.03*(3*0.01*0.01 + 0.03*0.03)}"
               iyy="${(1/12)*0.03*(3*0.01*0.01 + 0.03*0.03)}"
               izz="${0.5*0.03*0.01*0.01}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_wrist_joint" type="revolute">
    <parent link="left_forearm_link"/>
    <child link="left_wrist_link"/>
    <origin xyz="${forearm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <!-- FIXED: Limited wrist rotation to prevent self-collision -->
    <limit effort="10" velocity="4.0" lower="-1.57" upper="1.57"/>
    <dynamics damping="0.1" friction="0.02"/>
  </joint>

  <!-- Left gripper finger - IMPROVED FOR PICKUP -->
  <link name="left_finger_link">
    <visual>
      <origin xyz="${gripper_finger_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${gripper_finger_length}" radius="${finger_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${gripper_finger_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${gripper_finger_length}" radius="${finger_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.5</mu>
            <mu2>1.5</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="${gripper_finger_length/2} 0 0"/>
      <mass value="${finger_mass}"/>
      <inertia ixx="${(1/12)*finger_mass*(3*finger_radius*finger_radius + gripper_finger_length*gripper_finger_length)}"
               iyy="${(1/12)*finger_mass*(3*finger_radius*finger_radius + gripper_finger_length*gripper_finger_length)}"
               izz="${0.5*finger_mass*finger_radius*finger_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_finger_joint" type="revolute">
    <parent link="left_wrist_link"/>
    <child link="left_finger_link"/>
    <origin xyz="0.015 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- IMPROVED: Better gripper range for box pickup -->
    <limit effort="15" velocity="2.0" lower="-0.6" upper="0.6"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <!-- Left fingertip - IMPROVED GRIP -->
  <link name="left_fingertip_link">
    <visual>
      <geometry>
        <sphere radius="${gripper_tip_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision name="left_fingertip_collision">
      <geometry>
        <sphere radius="${gripper_tip_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>2.5</mu>
            <mu2>2.5</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <max_vel>0.01</max_vel>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               iyy="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               izz="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_fingertip_joint" type="fixed">
    <parent link="left_finger_link"/>
    <child link="left_fingertip_link"/>
    <origin xyz="${gripper_finger_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Right Gripper Arm Assembly (Mirror of left with FIXED CONSTRAINTS) -->
  <link name="right_shoulder_link">
    <visual>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.04" radius="0.02"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.1"/>
      <inertia ixx="${(1/12)*0.1*(3*0.02*0.02 + 0.04*0.04)}"
               iyy="${(1/12)*0.1*(3*0.02*0.02 + 0.04*0.04)}"
               izz="${0.5*0.1*0.02*0.02}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_shoulder_joint" type="revolute">
    <parent link="gripper_base_link"/>
    <child link="right_shoulder_link"/>
    <origin xyz="0 ${-gripper_base_width/3} 0" rpy="1.5708 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- FIXED: Mirror constraints to prevent backward bending -->
    <limit effort="30" velocity="2.0" lower="-1.2" upper="0.5"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <link name="right_upper_arm_link">
    <visual>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${upper_arm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${upper_arm_length/2} 0 0"/>
      <mass value="${upper_arm_mass}"/>
      <inertia ixx="${(1/12)*upper_arm_mass*(3*arm_radius*arm_radius + upper_arm_length*upper_arm_length)}"
               iyy="${(1/12)*upper_arm_mass*(3*arm_radius*arm_radius + upper_arm_length*upper_arm_length)}"
               izz="${0.5*upper_arm_mass*arm_radius*arm_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_shoulder_pitch_joint" type="revolute">
    <parent link="right_shoulder_link"/>
    <child link="right_upper_arm_link"/>
    <origin xyz="0 0 0.02" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- FIXED: Same constraints as left to prevent body collision -->
    <limit effort="30" velocity="2.0" lower="-0.8" upper="0.3"/>
    <dynamics damping="0.3" friction="0.1"/>
  </joint>

  <!-- Right elbow - FIXED CONSTRAINTS -->
  <link name="right_elbow_link">
    <visual>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.015"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="${(2/5)*0.05*0.015*0.015}"
               iyy="${(2/5)*0.05*0.015*0.015}"
               izz="${(2/5)*0.05*0.015*0.015}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_upper_arm_link"/>
    <child link="right_elbow_link"/>
    <origin xyz="${upper_arm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <!-- FIXED: Same constraints as left -->
    <limit effort="20" velocity="3.0" lower="-0.5" upper="1.8"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <!-- Right forearm -->
  <link name="right_forearm_link">
    <visual>
      <origin xyz="${forearm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${forearm_length}" radius="${arm_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${forearm_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${forearm_length}" radius="${arm_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="${forearm_length/2} 0 0"/>
      <mass value="${forearm_mass}"/>
      <inertia ixx="${(1/12)*forearm_mass*(3*arm_radius*arm_radius + forearm_length*forearm_length)}"
               iyy="${(1/12)*forearm_mass*(3*arm_radius*forearm_radius + forearm_length*forearm_length)}"
               izz="${0.5*forearm_mass*arm_radius*arm_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_forearm_joint" type="fixed">
    <parent link="right_elbow_link"/>
    <child link="right_forearm_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Right wrist - FIXED CONSTRAINTS -->
  <link name="right_wrist_link">
    <visual>
      <geometry>
        <cylinder length="0.03" radius="0.01"/>
      </geometry>
      <material name="morandi_soft_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.03" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.03"/>
      <inertia ixx="${(1/12)*0.03*(3*0.01*0.01 + 0.03*0.03)}"
               iyy="${(1/12)*0.03*(3*0.01*0.01 + 0.03*0.03)}"
               izz="${0.5*0.03*0.01*0.01}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_wrist_joint" type="revolute">
    <parent link="right_forearm_link"/>
    <child link="right_wrist_link"/>
    <origin xyz="${forearm_length} 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <!-- FIXED: Same constraints as left -->
    <limit effort="10" velocity="4.0" lower="-1.57" upper="1.57"/>
    <dynamics damping="0.1" friction="0.02"/>
  </joint>

  <!-- Right gripper finger - IMPROVED FOR PICKUP -->
  <link name="right_finger_link">
    <visual>
      <origin xyz="${gripper_finger_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${gripper_finger_length}" radius="${finger_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision>
      <origin xyz="${gripper_finger_length/2} 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <cylinder length="${gripper_finger_length}" radius="${finger_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>1.5</mu>
            <mu2>1.5</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <origin xyz="${gripper_finger_length/2} 0 0"/>
      <mass value="${finger_mass}"/>
      <inertia ixx="${(1/12)*finger_mass*(3*finger_radius*finger_radius + gripper_finger_length*gripper_finger_length)}"
               iyy="${(1/12)*finger_mass*(3*finger_radius*finger_radius + gripper_finger_length*gripper_finger_length)}"
               izz="${0.5*finger_mass*finger_radius*finger_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_finger_joint" type="revolute">
    <parent link="right_wrist_link"/>
    <child link="right_finger_link"/>
    <origin xyz="0.015 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <!-- IMPROVED: Better gripper range for box pickup -->
    <limit effort="15" velocity="2.0" lower="-0.6" upper="0.6"/>
    <dynamics damping="0.2" friction="0.05"/>
  </joint>

  <!-- Right fingertip - IMPROVED GRIP -->
  <link name="right_fingertip_link">
    <visual>
      <geometry>
        <sphere radius="${gripper_tip_radius}"/>
      </geometry>
      <material name="gripper_red"/>
    </visual>
    <collision name="right_fingertip_collision">
      <geometry>
        <sphere radius="${gripper_tip_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>2.5</mu>
            <mu2>2.5</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <max_vel>0.01</max_vel>
            <min_depth>0.001</min_depth>
          </ode>
        </contact>
      </surface>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${tip_mass}"/>
      <inertia ixx="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               iyy="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               izz="${(2/5)*tip_mass*gripper_tip_radius*gripper_tip_radius}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_fingertip_joint" type="fixed">
    <parent link="right_finger_link"/>
    <child link="right_fingertip_link"/>
    <origin xyz="${gripper_finger_length} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Beautiful Morandi-Colored Basket (Open-Top) -->
  <link name="basket_link">
    <!-- Basket base -->
    <visual name="basket_base_visual">
      <origin xyz="0 0 -0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.35 0.05"/>
      </geometry>
      <material name="morandi_sage"/>
    </visual>
    <!-- Basket walls (thinner for more capacity) -->
    <visual name="basket_front_visual">
      <origin xyz="0 0.17 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.02 0.2"/>
      </geometry>
      <material name="morandi_dusty_pink"/>
    </visual>
    <visual name="basket_back_visual">
      <origin xyz="0 -0.17 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.02 0.2"/>
      </geometry>
      <material name="morandi_dusty_pink"/>
    </visual>
    <visual name="basket_left_visual">
      <origin xyz="0.19 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.33 0.2"/>
      </geometry>
      <material name="morandi_warm_gray"/>
    </visual>
    <visual name="basket_right_visual">
      <origin xyz="-0.19 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.33 0.2"/>
      </geometry>
      <material name="morandi_warm_gray"/>
    </visual>
    <!-- Collision for basket (separate base and walls for precision) -->
    <collision name="basket_base_collision">
      <origin xyz="0 0 -0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.35 0.05"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.8</mu>
            <mu2>0.8</mu2>
          </ode>
        </friction>
        <contact>
          <ode>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
          </ode>
        </contact>
      </surface>
    </collision>
    <collision name="basket_front_collision">
      <origin xyz="0 0.17 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.02 0.2"/>
      </geometry>
    </collision>
    <collision name="basket_back_collision">
      <origin xyz="0 -0.17 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.4 0.02 0.2"/>
      </geometry>
    </collision>
    <collision name="basket_left_collision">
      <origin xyz="0.19 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.33 0.2"/>
      </geometry>
    </collision>
    <collision name="basket_right_collision">
      <origin xyz="-0.19 0 0.075" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.33 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0.075"/>
      <mass value="0.6"/>
      <inertia ixx="0.015" iyy="0.025" izz="0.035" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="basket_joint" type="fixed">
    <parent link="base_link"/>
    <child link="basket_link"/>
    <origin xyz="-0.2 0 0.15" rpy="0 0 0"/>
  </joint>

  <!-- LIDAR -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.05"/>
      </geometry>
      <material name="metallic_gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="0.2"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${base_height + 0.03}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin name="gazebo_ros_clock" filename="libgazebo_ros_clock.so"/>
  </gazebo>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>30</update_rate>
      <left_joint>wheel_left_joint</left_joint>
      <right_joint>wheel_right_joint</right_joint>
      <wheel_separation>${wheel_separation}</wheel_separation>
      <wheel_diameter>${2*wheel_radius}</wheel_diameter>
      <max_wheel_torque>30</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <command_topic>cmd_vel</command_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <update_rate>50</update_rate>
      <joint_name>wheel_left_joint</joint_name>
      <joint_name>wheel_right_joint</joint_name>
      <joint_name>gripper_lift_joint</joint_name>
      <joint_name>left_shoulder_joint</joint_name>
      <joint_name>left_shoulder_pitch_joint</joint_name>
      <joint_name>left_elbow_joint</joint_name>
      <joint_name>left_wrist_joint</joint_name>
      <joint_name>left_finger_joint</joint_name>
      <joint_name>right_shoulder_joint</joint_name>
      <joint_name>right_shoulder_pitch_joint</joint_name>
      <joint_name>right_elbow_joint</joint_name>
      <joint_name>right_wrist_joint</joint_name>
      <joint_name>right_finger_joint</joint_name>
      <joint_name>caster_joint</joint_name>
    </plugin>
  </gazebo>

  <gazebo reference="lidar_link">
    <sensor type="ray" name="laser_scanner">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.570796</min_angle>
            <max_angle>1.570796</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <topicName>scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
      <parameters>$(find gpu_slam_bot)/config/controllers.yaml</parameters>
    </plugin>
  </gazebo>

  <!-- Contact Sensors for Grippers -->
  <gazebo reference="left_fingertip_link">
    <sensor name="left_fingertip_contact" type="contact">
      <contact>
        <collision>left_fingertip_collision</collision>
      </contact>
      <plugin name="gazebo_ros_contact_sensor" filename="libgazebo_ros_contact_sensor.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <contact_topic>left_gripper_contact</contact_topic>
        <frame_name>left_fingertip_link</frame_name>
      </plugin>
      <always_on>1</always_on>
      <update_rate>100</update_rate>
    </sensor>
  </gazebo>

  <gazebo reference="right_fingertip_link">
    <sensor name="right_fingertip_contact" type="contact">
      <contact>
        <collision>right_fingertip_collision</collision>
      </contact>
      <plugin name="gazebo_ros_contact_sensor" filename="libgazebo_ros_contact_sensor.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <contact_topic>right_gripper_contact</contact_topic>
        <frame_name>right_fingertip_link</frame_name>
      </plugin>
      <always_on>1</always_on>
      <update_rate>100</update_rate>
    </sensor>
  </gazebo>

  <!-- Gazebo Material Properties -->
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo>

  <gazebo reference="wheel_left">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="wheel_right">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="caster_link">
    <material>Gazebo/Black</material>
    <mu1>0.0</mu1>
    <mu2>0.0</mu2>
  </gazebo>

  <gazebo reference="basket_link">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="gripper_base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="left_upper_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="right_upper_arm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_forearm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="right_forearm_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_finger_link">
    <material>Gazebo/Red</material>
    <mu1>2.0</mu1>
    <mu2>2.0</mu2>
  </gazebo>

  <gazebo reference="right_finger_link">
    <material>Gazebo/Red</material>
    <mu1>2.0</mu1>
    <mu2>2.0</mu2>
  </gazebo>

  <gazebo reference="left_fingertip_link">
    <material>Gazebo/Red</material>
    <mu1>2.5</mu1>
    <mu2>2.5</mu2>
  </gazebo>

  <gazebo reference="right_fingertip_link">
    <material>Gazebo/Red</material>
    <mu1>2.5</mu1>
    <mu2>2.5</mu2>
  </gazebo>

  <!-- Transmissions for ros2_control -->
  <transmission name="gripper_lift_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="gripper_lift_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="gripper_lift_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_finger_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_finger_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_finger_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_finger_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_finger_joint">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_finger_motor">
      <hardwareInterface>PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>