controller_manager:
  ros__parameters:
    update_rate: 50

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ["wheel_left_joint"]
  right_wheel: ["wheel_right_joint"]
  wheel_separation: 0.35
  wheel_radius: 0.07
  cmd_vel_timeout: 0.5
  publish_rate: 50
  use_odometry: true
  odom_frame_id: "odom"
  base_frame_id: "base_link"
  odometry_source: "encoders"

